# Generated by Django 4.2.14 on 2024-07-12 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('date', models.DateTimeField()),
                ('judgment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Civilian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Unknown', max_length=100)),
                ('last_name', models.CharField(default='Unknown', max_length=100)),
                ('drivers_license_number', models.CharField(max_length=20, unique=True)),
                ('address', models.CharField(default='Unknown', max_length=200)),
                ('warrants', models.TextField(blank=True, default='')),
                ('citations', models.ManyToManyField(blank=True, to='mdt.citation')),
            ],
        ),
        migrations.RemoveField(
            model_name='officer',
            name='name',
        ),
        migrations.AddField(
            model_name='officer',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='officer',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='officer',
            name='status',
            field=models.CharField(choices=[('10-8', 'On Duty'), ('10-7', 'Off Duty')], default='10-8', max_length=4),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='bolos',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='location',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='color',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='make',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.IntegerField(default=2000),
        ),
        migrations.CreateModel(
            name='DriversLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True)),
                ('attached_civilian', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mdt.civilian')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=6)),
                ('location', models.CharField(default='Unknown', max_length=200)),
                ('description', models.TextField(default='No description')),
                ('officers_attached', models.ManyToManyField(blank=True, to='mdt.officer')),
            ],
        ),
        migrations.AddField(
            model_name='civilian',
            name='registered_vehicles',
            field=models.ManyToManyField(blank=True, to='mdt.vehicle'),
        ),
        migrations.AddField(
            model_name='citation',
            name='attached_civilian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdt.civilian'),
        ),
        migrations.AddField(
            model_name='officer',
            name='attached_calls',
            field=models.ManyToManyField(blank=True, to='mdt.currentcall'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='registered_civilian',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mdt.civilian'),
        ),
    ]
